#!/data/data/com.termux/files/usr/bin/sh
if [ "debian" = "pacman" ] || [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
if [ -x "/data/data/com.termux/files/usr/bin/update-alternatives" ]; then
update-alternatives --install 				/data/data/com.termux/files/usr/bin/editor editor /data/data/com.termux/files/usr/bin/vim 50
update-alternatives --install 				/data/data/com.termux/files/usr/bin/vi vi /data/data/com.termux/files/usr/bin/vim 20
fi
fi
